"""
Live Match Day Companion

Polls football-data.org for live match events, detects score/status changes,
generates emotional fan reactions via Haiku, and streams them via SSE.

Includes a simulation mode for testing and portfolio demos.
"""

import asyncio
import json
import logging
import os
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional

import ai_response
import fan_enhancements

logger = logging.getLogger(__name__)

FOOTBALL_DATA_BASE = "https://api.football-data.org/v4"
PL_COMPETITION_ID = "PL"
POLL_INTERVAL = 60  # seconds between polls (free tier: 10 req/min)

# ─── Data Structures ──────────────────────────────────────────────


@dataclass
class MatchEvent:
    """A single detected event in a live match."""
    event_type: str  # kickoff, goal, goal_conceded, halftime, second_half, fulltime
    minute: str      # e.g., "23'" or "HT" or "FT"
    description: str  # Short factual description
    reaction: str     # Fan persona reaction (generated by Haiku)
    score_home: int
    score_away: int
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class MatchState:
    """Tracks the state of a single live match."""
    match_id: int
    home_team: str
    away_team: str
    home_score: int = 0
    away_score: int = 0
    status: str = "TIMED"  # TIMED, IN_PLAY, PAUSED, FINISHED
    minute: int = 0
    events: List[MatchEvent] = field(default_factory=list)
    last_poll: float = 0.0


# ─── Event Detection ──────────────────────────────────────────────


def detect_changes(prev: MatchState, current_data: Dict) -> List[Dict]:
    """Compare previous state to new API data and return detected events."""
    events = []
    new_status = current_data.get("status", prev.status)
    new_home = current_data.get("home_score", prev.home_score) or 0
    new_away = current_data.get("away_score", prev.away_score) or 0
    minute = current_data.get("minute", prev.minute) or 0

    # Kickoff
    if prev.status in ("TIMED", "SCHEDULED") and new_status == "IN_PLAY":
        events.append({
            "type": "kickoff",
            "minute": "0'",
            "desc": f"Kick-off! {prev.home_team} vs {prev.away_team} is underway!",
            "home": new_home, "away": new_away,
        })

    # Goal scored (home)
    if new_home > prev.home_score:
        for _ in range(new_home - prev.home_score):
            events.append({
                "type": "goal",
                "minute": f"{minute}'",
                "desc": f"GOAL! {prev.home_team} score! {new_home}-{new_away}",
                "home": new_home, "away": new_away,
            })

    # Goal scored (away)
    if new_away > prev.away_score:
        for _ in range(new_away - prev.away_score):
            events.append({
                "type": "goal_conceded" if True else "goal",  # perspective handled by reactor
                "minute": f"{minute}'",
                "desc": f"GOAL! {prev.away_team} score! {new_home}-{new_away}",
                "home": new_home, "away": new_away,
            })

    # Half-time
    if prev.status == "IN_PLAY" and new_status == "PAUSED":
        events.append({
            "type": "halftime",
            "minute": "HT",
            "desc": f"Half-time. {prev.home_team} {new_home}-{new_away} {prev.away_team}",
            "home": new_home, "away": new_away,
        })

    # Second half
    if prev.status == "PAUSED" and new_status == "IN_PLAY":
        events.append({
            "type": "second_half",
            "minute": "46'",
            "desc": f"Second half underway. {prev.home_team} {new_home}-{new_away} {prev.away_team}",
            "home": new_home, "away": new_away,
        })

    # Full-time
    if prev.status in ("IN_PLAY", "PAUSED") and new_status == "FINISHED":
        if new_home > new_away:
            result = f"{prev.home_team} win!"
        elif new_away > new_home:
            result = f"{prev.away_team} win!"
        else:
            result = "It's a draw!"
        events.append({
            "type": "fulltime",
            "minute": "FT",
            "desc": f"Full-time! {prev.home_team} {new_home}-{new_away} {prev.away_team}. {result}",
            "home": new_home, "away": new_away,
        })

    return events


# ─── Fan Reaction Generator ──────────────────────────────────────


def generate_reaction(event: Dict, club_id: str, home_team: str, away_team: str,
                      is_home_fan: bool) -> str:
    """Generate a short emotional fan reaction to a match event via Haiku."""
    enhanced = fan_enhancements.get_enhanced_persona(club_id, f"match against {away_team if is_home_fan else home_team}")
    mood = enhanced.get("mood", {})
    dialect = enhanced.get("dialect", {})
    dialect_inject = dialect.get("vocab_inject", "") if dialect else ""

    # Determine emotional context
    score_home, score_away = event["home"], event["away"]
    if is_home_fan:
        my_score, their_score = score_home, score_away
        my_team, their_team = home_team, away_team
    else:
        my_score, their_score = score_away, score_home
        my_team, their_team = away_team, home_team

    if my_score > their_score:
        emotional_state = "ECSTATIC — we're winning!"
    elif my_score < their_score:
        emotional_state = "FURIOUS — we're losing!"
    else:
        emotional_state = "TENSE — it's level!"

    event_desc = event["desc"]
    event_type = event["type"]

    system = f"""You are a passionate {my_team} fan watching a live match.
CURRENT SCORE: {home_team} {score_home}-{score_away} {away_team}
YOUR STATE: {emotional_state}
DIALECT: {dialect_inject}

Generate a SHORT, emotional live reaction (2-3 sentences MAX).
React like a real fan in the stadium — raw emotion, not analysis.
Use your dialect naturally. No hashtags or emojis in text."""

    prompt = f"[{event['minute']}] {event_desc}\n\nReact as a {my_team} fan watching live:"

    try:
        result = ai_response.call_anthropic_api(
            messages=[{"role": "user", "content": prompt}],
            system=system,
        )
        content = result.get("content", [])
        if isinstance(content, list) and content:
            return content[0].get("text", "...")
        return result.get("response", "...")
    except Exception as e:
        logger.warning("Reaction generation failed: %s", e)
        return "..."


# ─── Simulation Mode ──────────────────────────────────────────────

# Pre-recorded match scripts for testing and demo
SIMULATED_MATCHES = {
    "arsenal_bournemouth": {
        "home_team": "Arsenal",
        "away_team": "Bournemouth",
        "home_id": "arsenal",
        "away_id": "bournemouth",
        "events": [
            {"minute": 0, "status": "IN_PLAY", "home": 0, "away": 0, "delay": 0},
            {"minute": 23, "status": "IN_PLAY", "home": 1, "away": 0, "delay": 8},
            {"minute": 38, "status": "IN_PLAY", "home": 2, "away": 0, "delay": 8},
            {"minute": 45, "status": "PAUSED", "home": 2, "away": 0, "delay": 6},
            {"minute": 46, "status": "IN_PLAY", "home": 2, "away": 0, "delay": 5},
            {"minute": 58, "status": "IN_PLAY", "home": 2, "away": 1, "delay": 8},
            {"minute": 71, "status": "IN_PLAY", "home": 3, "away": 1, "delay": 8},
            {"minute": 85, "status": "IN_PLAY", "home": 3, "away": 2, "delay": 8},
            {"minute": 90, "status": "FINISHED", "home": 3, "away": 2, "delay": 6},
        ],
    },
    "liverpool_everton": {
        "home_team": "Liverpool",
        "away_team": "Everton",
        "home_id": "liverpool",
        "away_id": "everton",
        "events": [
            {"minute": 0, "status": "IN_PLAY", "home": 0, "away": 0, "delay": 0},
            {"minute": 12, "status": "IN_PLAY", "home": 0, "away": 1, "delay": 8},
            {"minute": 34, "status": "IN_PLAY", "home": 1, "away": 1, "delay": 8},
            {"minute": 45, "status": "PAUSED", "home": 1, "away": 1, "delay": 6},
            {"minute": 46, "status": "IN_PLAY", "home": 1, "away": 1, "delay": 5},
            {"minute": 67, "status": "IN_PLAY", "home": 2, "away": 1, "delay": 8},
            {"minute": 90, "status": "FINISHED", "home": 2, "away": 1, "delay": 8},
        ],
    },
    "wolves_man_city": {
        "home_team": "Wolverhampton",
        "away_team": "Manchester City",
        "home_id": "wolves",
        "away_id": "manchester_city",
        "events": [
            {"minute": 0, "status": "IN_PLAY", "home": 0, "away": 0, "delay": 0},
            {"minute": 15, "status": "IN_PLAY", "home": 0, "away": 1, "delay": 8},
            {"minute": 31, "status": "IN_PLAY", "home": 0, "away": 2, "delay": 8},
            {"minute": 45, "status": "PAUSED", "home": 0, "away": 2, "delay": 6},
            {"minute": 46, "status": "IN_PLAY", "home": 0, "away": 2, "delay": 5},
            {"minute": 55, "status": "IN_PLAY", "home": 1, "away": 2, "delay": 8},
            {"minute": 72, "status": "IN_PLAY", "home": 2, "away": 2, "delay": 8},
            {"minute": 88, "status": "IN_PLAY", "home": 3, "away": 2, "delay": 8},
            {"minute": 90, "status": "FINISHED", "home": 3, "away": 2, "delay": 6},
        ],
    },
}


async def run_simulation(match_key: str, club_id: str, queue: asyncio.Queue):
    """
    Replay a pre-recorded match, generating reactions for each event.
    Pushes MatchEvent dicts into the queue for SSE consumption.
    Runs Haiku calls in a thread executor to avoid blocking the event loop.
    """
    script = SIMULATED_MATCHES.get(match_key)
    if not script:
        await queue.put({"type": "error", "message": f"Unknown match: {match_key}"})
        await queue.put(None)
        return

    home_team = script["home_team"]
    away_team = script["away_team"]
    is_home_fan = (club_id == script["home_id"])

    state = MatchState(
        match_id=0,
        home_team=home_team,
        away_team=away_team,
    )

    # Push initial state
    await queue.put({
        "type": "match_info",
        "home_team": home_team,
        "away_team": away_team,
        "club_id": club_id,
    })

    loop = asyncio.get_event_loop()

    for step in script["events"]:
        if step["delay"] > 0:
            await asyncio.sleep(step["delay"])

        current_data = {
            "status": step["status"],
            "home_score": step["home"],
            "away_score": step["away"],
            "minute": step["minute"],
        }

        changes = detect_changes(state, current_data)

        state.home_score = step["home"]
        state.away_score = step["away"]
        state.status = step["status"]
        state.minute = step["minute"]

        for change in changes:
            # Run synchronous Haiku call in thread to avoid blocking
            reaction = await loop.run_in_executor(
                None, generate_reaction,
                change, club_id, home_team, away_team, is_home_fan
            )

            event = {
                "type": "event",
                "event_type": change["type"],
                "minute": change["minute"],
                "description": change["desc"],
                "reaction": reaction,
                "score_home": step["home"],
                "score_away": step["away"],
                "home_team": home_team,
                "away_team": away_team,
                "timestamp": datetime.utcnow().isoformat(),
            }

            await queue.put(event)

    await queue.put({"type": "end", "message": "Match finished"})
    await queue.put(None)


# ─── Live Polling (for real matches) ──────────────────────────────


async def poll_live_match(match_id: int, club_id: str, queue: asyncio.Queue):
    """
    Poll football-data.org for a specific live match.
    Pushes events into queue as they're detected.
    """
    import urllib.request

    api_key = os.environ.get("FOOTBALL_DATA_API_KEY", "")
    headers = {"X-Auth-Token": api_key} if api_key else {}
    url = f"{FOOTBALL_DATA_BASE}/matches/{match_id}"

    state = MatchState(match_id=match_id, home_team="", away_team="")
    initialized = False

    while True:
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=10) as response:
                data = json.loads(response.read().decode("utf-8"))

            match = data
            home_team = match.get("homeTeam", {}).get("name", "Home")
            away_team = match.get("awayTeam", {}).get("name", "Away")
            score = match.get("score", {})
            ft = score.get("fullTime", {})
            status = match.get("status", "TIMED")
            minute = match.get("minute")

            if not initialized:
                state.home_team = home_team
                state.away_team = away_team
                state.status = status
                state.home_score = ft.get("home") or 0
                state.away_score = ft.get("away") or 0
                initialized = True
                await queue.put({
                    "type": "match_info",
                    "home_team": home_team,
                    "away_team": away_team,
                    "club_id": club_id,
                    "match_id": match_id,
                })
                await asyncio.sleep(POLL_INTERVAL)
                continue

            current_data = {
                "status": status,
                "home_score": ft.get("home") or 0,
                "away_score": ft.get("away") or 0,
                "minute": minute or 0,
            }

            changes = detect_changes(state, current_data)

            state.home_score = current_data["home_score"]
            state.away_score = current_data["away_score"]
            state.status = status
            state.minute = minute or 0

            # Determine if fan supports home or away
            club_lower = club_id.lower().replace("_", " ")
            is_home_fan = club_lower in home_team.lower()

            loop = asyncio.get_event_loop()
            for change in changes:
                reaction = await loop.run_in_executor(
                    None, generate_reaction,
                    change, club_id, home_team, away_team, is_home_fan
                )
                await queue.put({
                    "type": "event",
                    "event_type": change["type"],
                    "minute": change["minute"],
                    "description": change["desc"],
                    "reaction": reaction,
                    "score_home": current_data["home_score"],
                    "score_away": current_data["away_score"],
                    "home_team": home_team,
                    "away_team": away_team,
                    "timestamp": datetime.utcnow().isoformat(),
                })

            if status == "FINISHED":
                await queue.put({"type": "end", "message": "Match finished"})
                await queue.put(None)
                return

        except Exception as e:
            logger.warning("Poll error for match %d: %s", match_id, e)

        await asyncio.sleep(POLL_INTERVAL)
